Notes 100 - Select a note #1055
bldrs-ai/Share pull request #1088
Opened 2024-04-03 10:36 UTC by OlegMoshkovich

#1055

2024-04-04 16:07 UTC, pablo-mayrgundter requested changes

2024-04-04 16:07 UTC, pablo-mayrgundter commented on cypress/e2e/notes-100/select-a-note.cy.js
> +      cy.setCookie('isFirstTime', '1')
Pls replace these 2 lines with a helper,  setCookie + visitHome

2024-04-05 13:49 UTC, OlegMoshkovich commented on cypress/e2e/notes-100/select-a-note.cy.js
> +      cy.setCookie('isFirstTime', '1')
cool. replaced.

2024-04-05 17:50 UTC, pablo-mayrgundter approved these changes

2024-04-05 21:33 UTC, merged