Add Issues/Notes
bldrs-ai/Share pull request #235
Opened 2022-06-21 11:00 UTC by OlegMoshkovich

2022-06-23 08:43 UTC, OlegMoshkovich commented
Morning! Addressed the store reset and the mobile drawer issues.

2022-06-24 12:14 UTC, OlegMoshkovich commented on src/Components/IssuesControl.jsx
>  import debug from '../utils/debug'
@pablo-mayrgundter can you please look over this file.

2022-06-24 12:14 UTC, OlegMoshkovich commented on src/Components/IssuesControl.jsx
> +  useEffect(()=>{
@pablo-mayrgundter please look over this

2022-06-25 13:59 UTC, pablo-mayrgundter requested changes

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/CameraControl.jsx
> + * @param {Object} v The IFC viewer, which contains the
should still be 'viewer'

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/CameraControl.jsx
> +/** @return {boolean} True if the camera hash params are present. */
Should be 'iff'.  See https://en.wikipedia.org/wiki/If_and_only_if

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/CameraControl.jsx
> +  if (!cameraControls ) {
This seems like an error.  Is there a valid case where this method is called with null/undefined?  If so pls document if not, throw error

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> +import Select from '../assets/2D_Icons/Select.svg'
Please sort svgs to bottom

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> +  useEffect(()=>{
Please format the arrow functions in this file

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> + * @param {string} contetne The comment title, optional
these params are out of sync

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> +export default function IssueCard({
So, it's not clear to me what's required or not here.  Anything that's actually required should have an assertDefined here before continuing to pass values downwards.

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssuesControl.jsx
> +import Next from '../assets/2D_Icons/NavNext.svg'
sort svgs to bottom

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/IssuesControl.jsx
> +      console.log('comments - fetch loop', selectedIssueId)
remove

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> +// import {removeCameraUrlParams} from './CameraControl'
remove

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> +          title='Notes'
format spaces around =, and below a few places

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> +          onClick = {
one line, and below

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +// import {isRunningLocally} from './network'
revert

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +    console.warn('Empty comments!')
debug()

2022-06-25 13:59 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +// class MockOctokit {
Remove the rest

2022-06-25 14:23 UTC, OlegMoshkovich commented on src/Components/CameraControl.jsx
> + * @param {Object} v The IFC viewer, which contains the
ok

2022-06-25 16:24 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2022-06-25 19:08 UTC, OlegMoshkovich reviewed
fixed spacing with eslint rules
@pablo-mayrgundter PTAL

2022-06-30 14:12 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> + * @param {string} url full url attached to GH issue with camera position
embeddedUrl

2022-06-30 14:14 UTC, pablo-mayrgundter commented on src/Components/IssueCard.jsx
> +      tabIndex={0}
looks like you still need to activate eslint spaces checking

2022-06-30 14:15 UTC, pablo-mayrgundter commented on src/Components/IssueCard.test.jsx
> +  render(<MockRoutes contentElt={<IssueCard id={id} index = {index} title = "new_title" />}/>)
same, spaces

2022-06-30 14:16 UTC, pablo-mayrgundter commented on src/Components/IssueCard.test.jsx
> +    embeddedUrl = " http://localhost:8080/share/v/p/index.ifc#c:-141.9,72.88,21.66,-43.48,15.73,-4.34" />}/>)
nice!

2022-06-30 14:17 UTC, pablo-mayrgundter commented on src/Components/IssueControl.test.jsx
> +    title: 'TEST_ISSUE_TITLE_1',
can you use a different title and body throughout?  I suggest 2 sentences with a few words each.  These will live with us for a while and will help us test preview, etc. later on

2022-06-30 14:18 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> -      <CameraControl viewer={viewer}/>
good to see consistent style, but i think to minimize change for now we should use no spaces, as in discussion on discorc

2022-06-30 14:19 UTC, pablo-mayrgundter commented on src/Components/SideDrawer.jsx
> +            <div className={classes.content}>
spaces in whole file

2022-06-30 14:23 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +// import {isRunningLocally} from './network'
I do think we want this check for running local.. the problem is that if you use live comments from GitHub when developing you can quickly hit per-user quota limits.  I added this to use the test comments when developing and then flip them when I ready to test with more realistic data.

2022-06-30 14:24 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> + * The comments should have the following structure:
Stale comment?

2022-06-30 14:25 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +      {
yep, that's right

2022-06-30 14:25 UTC, pablo-mayrgundter commented on src/utils/GitHub.js
> +// const octokit = isRunningLocally() ? new MockOctokit() : new Octokit({
please restore unless you found a good reason not to

2022-07-01 14:14 UTC, pablo-mayrgundter commented
Code is looking good.  But comment link doesn't open the issue panel!

https://deploy-preview-235--bldrs-share.netlify.app/share/v/p/index.ifc/89/112/139/154/265#c:22.29,49.57,82.32,29.19,6.12,-9.25::i:1257156364

This brings me to the correct item in the scene, but the issue panel isn't open.  When i do open it, the issue isn't selected.

2022-07-06 22:13 UTC, OlegMoshkovich commented on src/Components/SideDrawer.jsx
> +export default function SideDrawerWrapper() {
@pablo-mayrgundter added the wrapper

2022-07-06 22:13 UTC, OlegMoshkovich commented on src/Components/SideDrawer.test.jsx
> +test('side drawer - issues id in url', () => {
@pablo-mayrgundter side drawer test

2022-07-06 22:15 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2022-07-07 11:32 UTC, pablo-mayrgundter requested changes
Let's talk about the last unit test to exercise the code getting the hash from useLocation through to IssueCard

2022-07-07 11:32 UTC, pablo-mayrgundter commented on src/Containers/CadView.jsx
> -    // The spatial structure doesn't contain properties.  NavTree uses
Looks like a bad merge.. this is live in prod and should be included.

2022-07-07 11:32 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> +  console.log('selected element', selectedElement)
remove

2022-07-07 11:32 UTC, pablo-mayrgundter commented on src/Components/SideDrawer.test.jsx
> +    result.current.setSelectedIssueId(Number(extractedCommentId))
This simulates the after-effect of an issue in the URL.  I think IssuesControl   We also need to ensure the trip from the the URL to here.

2022-07-07 12:43 UTC, OlegMoshkovich commented on src/utils/GitHub.js
> +  console.log('comments', comments)
all of the console logs are outdated. - not sure why it is showing up here.

2022-07-08 07:33 UTC, pablo-mayrgundter approved these changes

2022-07-08 07:33 UTC, pablo-mayrgundter commented on src/Components/SideDrawer.test.jsx
> +test('side drawer - issues id in url', () => {
Thanks!

2022-07-08 07:33 UTC, pablo-mayrgundter commented on src/Components/SideDrawer.jsx
> +export default function SideDrawerWrapper() {
ok

2022-07-08 07:33 UTC, pablo-mayrgundter commented on src/Components/IssuesControl.jsx
> +    const fetchIssues = async () => {
Please add:
```
// TODO(pablo): refactor issues fetch logic into Issues.js
```

2022-07-08 07:34 UTC, pablo-mayrgundter commented
Please add the one TODO comment I noted, then all good!

2022-07-08 08:07 UTC, pablo-mayrgundter commented
Actually, I want to base some changes off of this so will merge now and add the todo.

2022-07-08 08:07 UTC, merged