Reset the comments state when the next note is selected -- #257
bldrs-ai/Share pull request #266
Opened 2022-07-13 18:19 UTC by OlegMoshkovich

2022-07-14 08:20 UTC, pablo-mayrgundter commented
Heya, looks like a draft?

2022-07-15 18:32 UTC, OlegMoshkovich commented
yes - it is. will mark it as such.

2022-07-15 18:57 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL!

2022-07-17 12:09 UTC, pablo-mayrgundter commented
Heya, I'm not seeing this in prod anymore, but I'm also seeing the side panel close when I click on comments, but only sometimes.  Not really sure what the state of prod is atm.

2022-07-19 19:07 UTC, pablo-mayrgundter commented
Not sure what this is fixing then.. "This PR addresses the issue state slice -, particularly the comments portion."  I don't follow.

Sidebar disappears when I click on second comment to an issue.

Also, the green highlight on the comments button shows up when comments are inactive, but I think you want it when they're active.

Let's do a call if this is getting confusing

2022-07-19 22:31 UTC, OlegMoshkovich reviewed
@pablo-mayrgundter left descriptions.

2022-07-19 22:31 UTC, OlegMoshkovich commented on src/Components/IssuesControl.jsx
> +        if (commentsData) {
@pablo-mayrgundter - this PR is about this if statement. 
commentsData is undefined when no comments were attached to the issue, which was causing the error int he pull logic and the state would never reset.

2022-07-19 22:31 UTC, OlegMoshkovich commented on src/store/IssuesSlice.js
> -    replies: [],
corrected the language here.

2022-07-19 22:31 UTC, OlegMoshkovich commented on src/utils/GitHub.js
> +      body: 'The Architecture, Engineering and Construction industries are trying to face challenging problems of the future with tools anchored in the past. Meanwhile, a new dynamic has propelled th
Added image url to the body to test the images attached to comments.

2022-07-21 14:54 UTC, pablo-mayrgundter requested changes

2022-07-21 14:54 UTC, pablo-mayrgundter commented on src/Components/IssuesControl.jsx
> +        console.log('1 Issue index - ', index)
remove debug

2022-07-21 14:54 UTC, pablo-mayrgundter commented on src/Components/OperationsGroup.jsx
> +    border: (props) => props.isCommentsOn ? 'none' : '1px solid lime',
Is this the intended behavior?  Thought I commented on this but I don't see my review anymore.

I was expecting the highlight to show up when comments are active, but be off when they're not.  This is inverted.  Happy to discuss.

2022-07-21 14:54 UTC, pablo-mayrgundter commented on src/Components/SampleModelsControl.jsx
> +      1: '/share/v/gh/OlegMoshkovich/BLDRS_models/main/haus.ifc',
Is this debug?

2022-07-22 19:38 UTC, OlegMoshkovich reviewed
seems all concerns were addressed and the PR is ready to be merged.
correct?

2022-07-22 20:07 UTC, pablo-mayrgundter approved these changes
LGTM!  Go ahead :)

2022-07-22 21:00 UTC, merged