notes drawer styles
bldrs-ai/Share pull request #308
Opened 2022-08-03 14:40 UTC by OlegMoshkovich

Adjusted:
- Notes panel NavBar
- Note card

2022-08-03 16:50 UTC, OlegMoshkovich commented
@pablo-mayrgundter please take a look

2022-08-03 17:15 UTC, pablo-mayrgundter commented
Looking better!  There's a problem with paging.. load KNIK and then page issues.. you can get to 3/4 but not to 4/4.

2022-08-03 17:17 UTC, pablo-mayrgundter commented
Mobile (iPhone12) looks to have too much padding..

<img width="194" alt="image" src="https://user-images.githubusercontent.com/2480879/182669477-3200bf11-3d69-4816-9daf-b5d98ae59593.png">

2022-08-03 17:17 UTC, pablo-mayrgundter requested changes
/docs directory shouldn't be part of this or future PRs.  Did you sync to head to create this branch?  Might want to restart it..

2022-08-03 17:21 UTC, pablo-mayrgundter commented
This looks like it's pulling in Markus's proposal to remove metadata.

Could you list in the description which issues you're addressing with this PR?

I don't agree with that change.. I think it's right for smth like Portfolio mode when we have that, but in general I think it helps orient the user that these are indeed comments to see the usual metadata.

2022-08-03 17:36 UTC, pablo-mayrgundter commented
How about omiting the pager when there's only a single issue? 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/2480879/182673005-b8cea011-84c4-48f0-b4b4-00e3f7406488.png">

2022-08-04 10:53 UTC, OlegMoshkovich commented
Address the following issues:
https://github.com/bldrs-ai/Share/issues/304
part of this issue
https://github.com/bldrs-ai/Share/issues/306
part of this issue
https://github.com/bldrs-ai/Share/issues/305

2022-08-04 11:59 UTC, pablo-mayrgundter commented
Did left padding grow?  I thought this was left-aligned with "Notes" before.. 
<img width="212" alt="image" src="https://user-images.githubusercontent.com/2480879/182841691-930cdeab-c157-4336-93ff-1020da67a6fd.png">

2022-08-04 14:11 UTC, OlegMoshkovich commented
<img width="745" alt="image" src="https://user-images.githubusercontent.com/3433606/182868384-daee5246-c692-46f5-9820-16b06ec77986.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/3433606/182868468-d25c4672-feaa-4b2c-b4c1-1c734ccae205.png">

2022-08-04 15:23 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2022-08-04 15:35 UTC, pablo-mayrgundter approved these changes
LGTM. 

One change for unit tests.. looks like you removed the assert for username in previous change, but should be back now.  Added comment below...

2022-08-04 15:35 UTC, pablo-mayrgundter commented on src/Components/IssueCard.test.jsx
> -  expect(screen.getByText('bob')).toBeInTheDocument()
Shouldn't this be included?

2022-08-04 15:35 UTC, pablo-mayrgundter commented on src/Components/IssuesControl.jsx
> +            {/* <div style={{fontSize: '10px'}}> {selectedIssueIndex + 1} of {issues.length}</div> */}
remove

2022-08-04 17:07 UTC, merged