Created cut plane form normal and point
bldrs-ai/Share pull request #332
Opened 2022-08-15 12:23 UTC by OlegMoshkovich

This PR is addressing #153.
Add a basic menu to the cut plane UI that allows the user to create a cut plane at the center of the model on one of the axes.
Introduced plane hash URL(:p) parameter.

2022-08-15 21:45 UTC, pablo-mayrgundter commented
Heya, I think this still qualifies as draft since it's not working quite yet.  Sound right?

2022-08-16 09:02 UTC, OlegMoshkovich commented
yes, not sure why it is switched to normal pr.

2022-08-18 21:32 UTC, OlegMoshkovich commented
@pablo-mayrgundter were you able to get any more clarity about why the plane is not cutting through the model?

2022-08-20 00:48 UTC, mkeshavarzi requested changes

2022-08-20 00:48 UTC, mkeshavarzi commented on src/utils/cutPlane.js
> +export function getModelCenter(ifcModel) {
Hey Oleg, if you change the return of this function to new Vec3, the section plane should work:

```
export function getModelCenter(ifcModel) {
  return new Vector3(
    (ifcModel?.geometry.boundingBox.max.x +
      ifcModel?.geometry.boundingBox.min.x) /
    2,
    (ifcModel?.geometry.boundingBox.max.y +
      ifcModel?.geometry.boundingBox.min.y) /
    2,
    (ifcModel?.geometry.boundingBox.max.z +
      ifcModel?.geometry.boundingBox.min.z) /
    2,
  )
}
```

2022-08-21 02:54 UTC, mkeshavarzi approved these changes
Looks great!

2022-08-22 15:05 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2022-08-22 15:26 UTC, pablo-mayrgundter requested changes
Tests please.  Likes in issues, url -> function, button -> function, clear.

2022-08-22 15:34 UTC, pablo-mayrgundter commented
Is it intended that only one cut plain is active at a time?  Would be nice to support multiple if it fits in this PR.

2022-08-22 16:07 UTC, OlegMoshkovich commented
Yes one for now. 
The scope feels right, and useful.

2022-08-22 16:08 UTC, OlegMoshkovich commented
tests .. yes, will add.

2022-08-23 10:46 UTC, OlegMoshkovich commented
Testing successfully getting to create plane function.
It requires a viewer.
how do we test viewer functionality? 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/3433606/186139114-af568761-cf18-48b6-bec7-b38cf2d66ba7.png">

2022-08-23 21:10 UTC, pablo-mayrgundter commented
if you're testing A, and A calls B, and B is a mess to test, then you "mock" B
```
jest.mock('../B')
const b = require('../B')

// b is a mock function
b.mockImplementation(() => 42)
b()
// > 42
```
See docs here: https://jestjs.io/docs/mock-functions#mock-implementations

2022-08-23 21:19 UTC, OlegMoshkovich commented
I see.. so in this case we would need to create viewer mock which contains a clipper and deleteAllPlaces methods?

2022-08-24 20:04 UTC, OlegMoshkovich commented
@pablo-mayrgundter created checklist in the #153 
everything is complete besides the tests, and those are stubbed out.
Can you please help with the test to make it production ready?
This is issue is on a critical path.

2022-08-26 03:35 UTC, mkeshavarzi commented on src/utils/cutPlane.js
> -function removePlanes(viewer) {
Hey @OlegMoshkovich - is there a reason why we are removing these helper functions? I am using the ``removePlanes`` for the extract level feature.

2022-08-30 19:00 UTC, pablo-mayrgundter commented
> 

Ok, please merge in #358, with the improved web-ifc-viewer mock.  Then try following the CadView.test for how to go from URL -> asserts on IFCjs.

2022-09-05 18:16 UTC, pablo-mayrgundter commented
Heya, looking back at your original question about testing, you'll want to add a jest.fn() mock method to __mocks__/web-ifc-viewer.js for viewer.clipper.deleteAllPlanes and assert on it after your code-under-test.  Hope that helps!

2022-09-09 10:18 UTC, OlegMoshkovich commented on src/Components/CutPlaneMenu.test.jsx
> +    debug()
how do I reference the mock viewer in the test?

2022-09-09 12:11 UTC, OlegMoshkovich commented on src/Components/CutPlaneMenu.test.jsx
> +    await act(() => {
this does it.

2022-09-09 12:12 UTC, OlegMoshkovich commented on src/Components/CutPlaneMenu.jsx
> +  const viewer = useStore((state) => state.viewerStore)
viewer is pulled from the store - so it needs to be in the store.

2022-09-09 12:48 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2022-09-09 14:45 UTC, pablo-mayrgundter approved these changes
Wowow!  Super jağ!

2022-09-09 14:48 UTC, merged