Fix property set scrolling
bldrs-ai/Share pull request #333
Opened 2022-08-16 10:56 UTC by OlegMoshkovich

- This pr addresses scrolling for the psets, previously the psets in the expanded view did not scroll all the way.
- Change mobile drawer to full height when it is initially opened.

2022-08-16 22:44 UTC, pablo-mayrgundter requested changes
Looks like you got an unexpected file included in this

2022-08-16 22:44 UTC, pablo-mayrgundter commented on src/utils/cutPlane.js
> +import {Box3, BufferAttribute, BufferGeometry, Mesh, Vector3} from 'three'
I think remove this file from the PR?

2022-08-17 21:39 UTC, OlegMoshkovich commented
removed. PTAL

2022-08-19 16:29 UTC, pablo-mayrgundter approved these changes

2022-08-19 16:32 UTC, merged