WIP: Notes: Custom order
bldrs-ai/Share pull request #352
Opened 2022-08-24 15:18 UTC by OlegMoshkovich

this

2022-08-24 20:10 UTC, OlegMoshkovich reviewed
Some comments for the utility functions
This is still work in progress, but the structure is emerging.
@pablo-mayrgundter if you have time, please take a look and comment.

2022-08-30 20:49 UTC, pablo-mayrgundter requested changes

2022-08-30 20:49 UTC, pablo-mayrgundter commented on src/utils/objects.js
> +export function sortObjectsByKey(array, key) {
Cool.  Test pls.

2022-08-30 20:49 UTC, pablo-mayrgundter commented on src/utils/strings.js
> +  let extractedNumber
I think for this we should find or write a markdown plugin.   Check out the docs here: https://www.npmjs.com/package/react-markdown#api

2022-08-30 20:49 UTC, pablo-mayrgundter commented on src/utils/strings.js
> +export function extractBodyContent(str) {
Neato :) Not sure if this is better plugin or not.  Can you try doing extract above as a plugin and then let's see?

2022-10-02 05:54 UTC, OlegMoshkovich commented on src/utils/strings.js
> +export function extractBodyContent(str) {
how do you mean plugin?

2022-10-12 09:15 UTC, OlegMoshkovich commented
@pablo-mayrgundter 
This PR is blocking me.
I cannot find a plug-in.
Seems like a more involved effort.
closing it.

2022-10-12 09:15 UTC, closed without merging