Bring the dialogs up in z value
bldrs-ai/Share pull request #699
Opened 2023-03-29 13:43 UTC by OlegMoshkovich

2023-03-29 15:22 UTC, oo-bldrs requested changes
There's a failing end-to-end test as a result of this change.

2023-03-29 15:22 UTC, oo-bldrs commented on src/Components/Dialog.jsx
Is there a MUI component that will use the browser's native `<dialog>` element to avoid the z-index wars?

https://developer.chrome.com/blog/what-is-the-top-layer/

2023-03-29 15:27 UTC, OlegMoshkovich commented on src/Components/Dialog.jsx
I think this is the only dialog component
https://mui.com/material-ui/api/dialog/
The tests are failing because of time out, rerunning the tests now.

2023-03-31 08:03 UTC, OlegMoshkovich commented
The tests are failing because of the timeout, it happens sometimes. Do you know why?

2023-03-31 08:22 UTC, OlegMoshkovich commented
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3433606/229066328-add10953-f755-417e-afc2-b00c99891252.png">

2023-08-03 16:42 UTC, closed without merging