Dialog+tabs
bldrs-ai/Share pull request #782
Opened 2023-08-12 00:43 UTC by pablo-mayrgundter

Changes:

- DialogTabs
  - Changed name to TabbedDialog
  - Remove actions to be part of content; not sure about this
  - Make more params optional
  - Changed param names; part to follow convention, part opinion.. see what you think
  - Bunch of typo fixes
- Simplify fixture setup

2023-08-12 07:45 UTC, OlegMoshkovich commented
![Uploading image.png…]()

2023-08-12 07:46 UTC, OlegMoshkovich commented
<img width="515" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/90b89c71-0dd1-4990-82aa-df00d08b483c">

2023-08-12 07:50 UTC, OlegMoshkovich commented
<img width="511" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/50ac18f8-e017-450d-b2b6-e2b60e3deed8">

<img width="485" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/6c45cdf6-efc4-42d3-b5d8-cb9af2de6d38">



Why remove the action button?

2023-08-12 07:53 UTC, OlegMoshkovich commented
If we remove the action button from the dialog actions, we break MUI convention, and I thought we decided to stick to it, so it more cohesive.
<img width="660" alt="image" src="https://github.com/bldrs-ai/Share/assets/3433606/7355db30-16b9-4710-8e69-380218f1209a">

2023-08-12 08:10 UTC, OlegMoshkovich reviewed
Much cleaner props!
Regarding the action button, if we remove it, we break MUI convention.
I thought we decided to stick to it, so it more cohesive. 
Having the button in the dialog actions also takes care of the spacing issue, that way it is always in the same place.

This is the design using MUI current system.
https://www.figma.com/file/DqKVaQEukf8vVHnlwiRGhv/Screens?type=design&node-id=2362-16501&mode=design&t=q4QyRjLNsdaT4r9i-0
What do you think about implementing it exactly as it is specified?

This is the master component sheet for the dialog:
https://www.figma.com/file/0WnF8npo2MGNmSgKKtnPuo/MUI-for-Figma-Material-UI-v5.14.0?type=design&node-id=6586-47137&mode=design&t=1s6f2SCSWGYpzfkk-0

2023-08-14 16:18 UTC, pablo-mayrgundter commented
Ok, moved DialogActions back in.  PTAL

2023-08-14 16:25 UTC, OlegMoshkovich commented
title disappeared.

2023-08-15 13:00 UTC, OlegMoshkovich requested changes
Several comments.

2023-08-17 00:37 UTC, pablo-mayrgundter commented on src/Components/TabbedDialog.fixture.jsx
> +      setIsDialogDisplayed={() => debug().log('setIsDialogDisplayed')}
Done

2023-08-17 00:37 UTC, pablo-mayrgundter commented
PTAL

2023-08-17 12:26 UTC, OlegMoshkovich approved these changes

2023-08-17 20:29 UTC, merged

2023-08-17 20:30 UTC, pablo-mayrgundter commented
Cypress is either stuck or taking too long to run.  I just ran locally no issues.  Submitting.