Add qr code to share dialog
bldrs-ai/Share pull request #797
Opened 2023-10-02 11:24 UTC by OlegMoshkovich

This PR:

- adds react-qr-code library
- adds QR code to the share dialog

2023-10-02 11:30 UTC, OlegMoshkovich commented
@pablo-mayrgundter PTAL

2023-10-03 18:51 UTC, pablo-mayrgundter requested changes
Unit test pls.. just check that it's there.

2023-10-05 13:53 UTC, OlegMoshkovich commented
@pablo-mayrgundter added tests PTAL

2023-10-05 13:54 UTC, OlegMoshkovich reviewed
@pablo-mayrgundter added qr test - PTAL

2023-10-05 13:54 UTC, pablo-mayrgundter approved these changes

2023-10-05 14:05 UTC, merged